image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Node & Playwright
    init: |
      npm install
      npx playwright install
    command: |
      npx playwright test

vscode:
  extensions:
    - ms-playwright.playwright

ports:
  - port: 9323
    onOpen: open-preview
    description: Playwright HTML report (if generated)
